version: '2.4'
services:
  postgres:
    image: postgres:15.0
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: cqrs_booking_kata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
