apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: event-bus
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    # TODO: pass variables
    value: "amqp://localhost:5673"
