name: E2E tests (Express)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  e2e_tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./express

    steps:
    - uses: actions/checkout@v3.2.0

    - name: Set up Node
      uses: actions/setup-node@v3.5.1
      with:
        node-version: ">=18.3.0"

    - run: npm i -g yarn
    - run: yarn install && yarn docker:test
    - run: RABBIT_PORT=5673 PG_PORT=5435 PG_PASSWORD=postgres npx jest
    --detectOpenHandles --forceExit  --runInBand --config jest.e2e.config.js
